### ISSUE TITLE
Plausible stats on website?

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/www-data#19]
Plausible is now tracking all access to the dist0rtion.com website.
The dashboard is currently public under this URL: https://plausible.io/dist0rtion.com

Do we want it to remain public?
Do we want to include it somewhere on our website?

**Comment by vrde** [comment]
> Do we want it to remain public?

Yep.

> Do we want to include it somewhere on our website?

Yep.

Happy to hear other opinions.
